name: Push SocialNetwork
concurrency: ci-socialNetwork

on:
  push: 
    branches: [ master ]
    paths: 
      - 'socialNetwork/**'

env:
  IMAGE_BASE_NAME: 'deathstarbench/social-network-microservices'
  REPO_PATH: 'socialNetwork'
  TAG_PREFIX: 'socialNetwork'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0 
    - name: Log into Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_REGISTRY_LOGIN }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    - name: Calculate new version
      id: new-version
      uses: codacy/git-version@2.4.0
      with:
        prefix: "${{ env.TAG_PREFIX }}-"
        log-paths: "${{ env.REPO_PATH }}/"
      if: github.ref == 'refs/heads/master'
    - name: Create tag
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/${{ steps.new-version.outputs.VERSION }}',
            sha: context.sha
          })
        - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: ${{ env.REPO_PATH }}
        push: true
        tags:
          - ${{ env.IMAGE_BASE_NAME }}:latest
          - ${{ env.IMAGE_BASE_NAME }}:${{ steps.new-version.outputs.VERSION }}
