name: Push SocialNetwork
concurrency: ci-socialNetwork

on:
  push: 
    branches: [ master ]
    paths: 
      - 'socialNetwork/**'

env:
  MICROSERVICES_IMAGE_NAME: 'deathstarbench/social-network-microservices'
  MEDIA_FRONTEND_IMAGE_NAME: 'deathstarbench/social-network-media-frontend'
  OPENRESTY_THRIFT_IMAGE_NAME: 'deathstarbench/social-network-openresty-thrift'
  REPO_PATH: 'socialNetwork'
  TAG_PREFIX: 'socialNetwork'

jobs:
  create-github-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0

    - name: Calculate new version
      id: new-version
      uses: codacy/git-version@2.4.0
      with:
        prefix: "${{ env.TAG_PREFIX }}-"
        log-paths: "${{ env.REPO_PATH }}/"
      if: github.ref == 'refs/heads/master'

    - name: Create tag
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/${{ steps.new-version.outputs.VERSION }}',
            sha: context.sha
          })

    - name: Write version number to environment
      run: echo VERSION=${{ steps.new-version.outputs.VERSION }} >> $GITHUB_ENV

  publish-microservices:
    needs: create-github-tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log into Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_REGISTRY_LOGIN }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: ${{ env.REPO_PATH }}
        push: true
        tags:
          - ${{ env.MICROSERVICES_IMAGE_NAME }}:latest
          - ${{ env.MICROSERVICES_IMAGE_NAME }}:${{ env.VERSION }}

  publish-media-frontend:
    needs: create-github-tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log into Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_REGISTRY_LOGIN }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: ${{ env.REPO_PATH }}/docker/media-frontend/xenial
        push: true
        tags:
          - ${{ env.MEDIA_FRONTEND_IMAGE_NAME }}:latest
          - ${{ env.MEDIA_FRONTEND_IMAGE_NAME }}:${{ env.VERSION }}

  publish-openresty-thrift:
    needs: create-github-tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log into Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_REGISTRY_LOGIN }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: ${{ env.REPO_PATH }}/docker/openresty-thrift/xenial
        push: true
        tags:
          - ${{ env.OPENRESTY_THRIFT_IMAGE_NAME }}:latest
          - ${{ env.OPENRESTY_THRIFT_IMAGE_NAME }}:${{ env.VERSION }}
